### ISSUE TITLE
App does not run

### ISSUE THREAD

**Issue by smithaitufe** [heruan/aurelia-route-mapper-example#1]
I did npm install then I ran npm run server, it threw an error.
I did npm start, it also threw error.

Here is the log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle aurelia-route-mapper-example@0.1.0~prestart: aurelia-route-mapper-example@0.1.0
6 silly lifecycle aurelia-route-mapper-example@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle aurelia-route-mapper-example@0.1.0~start: aurelia-route-mapper-example@0.1.0
8 verbose lifecycle aurelia-route-mapper-example@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle aurelia-route-mapper-example@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Directory\Dev\aurelia\tutorials\aurelia-route-mapper-example\node_modules\.bin;C:\app\client\Smith Aitufe\product\12.1.0\client_1;C:\app\client\Smith Aitufe\product\12.1.0\client_1\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;c:\oraclexe\app\oracle\product\11.2.0\server;c:\oraclexe\app\oracle\product\11.2.0\server\bin;c:/oraclexe/app/oracle/product/11.2.0/server/bin;C:\Program Files (x86)\PC Connectivity Solution\;C:\Python34\;C:\Python34\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\ImageMagick;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\MySQL\MySQL Server 5.6\bin;C:\Program Files\erl7.0\bin;C:\Program Files\PostgreSQL\9.4\bin;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.2\bin;C:\Android\sdk\platform-tools;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Heroku\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\scala\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Elixir\bin;C:\Windows\system32\config\systemprofile\.mix\escripts;C:\Program Files (x86)\PuTTY\;C:\Ruby23\bin;C:\Users\Smith Aitufe\.dnx\bin;C:\Users\Smith Aitufe\AppData\Local\atom\bin;C:\Users\Smith Aitufe\AppData\Local\.meteor\;C:\Users\Smith Aitufe\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\scala\bin;C:\Program Files (x86)\Play\typesafe-activator-1.3.10\activator-dist-1.3.10\bin
10 verbose lifecycle aurelia-route-mapper-example@0.1.0~start: CWD: C:\Directory\Dev\aurelia\tutorials\aurelia-route-mapper-example
11 silly lifecycle aurelia-route-mapper-example@0.1.0~start: Args: [ '/d /s /c', 'npm run server' ]
12 silly lifecycle aurelia-route-mapper-example@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle aurelia-route-mapper-example@0.1.0~start: Failed to exec start script
14 verbose stack Error: aurelia-route-mapper-example@0.1.0 start: `npm run server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid aurelia-route-mapper-example@0.1.0
16 verbose cwd C:\Directory\Dev\aurelia\tutorials\aurelia-route-mapper-example
17 error Windows_NT 6.2.9200
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error aurelia-route-mapper-example@0.1.0 start: `npm run server`
22 error Exit status 1
23 error Failed at the aurelia-route-mapper-example@0.1.0 start script 'npm run server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aurelia-route-mapper-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server
23 error You can get their info via:
23 error     npm owner ls aurelia-route-mapper-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by smithaitufe** [comment]
I am closing this issue because it finally worked when I changed the webpack and webpack-dev-server dependency versions to 
```
 "webpack": "2.1.0-beta.13",
   "webpack-dev-server": "2.1.0-beta.0"
```
. Thanks for this example
